I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\david\\Documents\\Misc Coding\\VN\\Job Training Game\\game\\saves\\navigation.json.new' -> 'C:\\Users\\david\\Documents\\Misc Coding\\VN\\Job Training Game\\game\\saves\\navigation.json'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\david\Downloads\renpy-8.3.2-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Users\david\Downloads\renpy-8.3.2-sdk\renpy\main.py", line 599, in main
    renpy.dump.dump(False)
  File "C:\Users\david\Downloads\renpy-8.3.2-sdk\renpy\dump.py", line 262, in dump
    os.rename(new, filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\david\\Documents\\Misc Coding\\VN\\Job Training Game\\game\\saves\\navigation.json.new' -> 'C:\\Users\\david\\Documents\\Misc Coding\\VN\\Job Training Game\\game\\saves\\navigation.json'

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.2.24090902
Information and Security Awareness Training 101 1.0
Mon Dec 30 00:27:23 2024
